import {
  AlertTriangle,
  Banknote,
  BarChart3,
  BookOpen,
  Brain,
  CheckCircle,
  ClipboardList,
  FilePlus,
  FileText,
  GraduationCap,
  Inbox,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Package,
  Receipt,
  ShieldCheck,
  Star,
  Store,
  Upload,
  Users,
  Wallet,
  type LucideIcon
} from "lucide-react";
import type { IconName } from "@/lib/types";

export const ICONS: Record<IconName, LucideIcon> = {
  "clipboard-list": ClipboardList,
  "file-plus": FilePlus,
  "book-open": BookOpen,
  inbox: Inbox,
  wallet: Wallet,
  "life-buoy": LifeBuoy,
  store: Store,
  users: Users,
  "check-circle": CheckCircle,
  "shield-check": ShieldCheck,
  "alert-triangle": AlertTriangle,
  "graduation-cap": GraduationCap,
  "layout-dashboard": LayoutDashboard,
  "list-checks": ListChecks,
  receipt: Receipt,
  banknote: Banknote,
  upload: Upload,
  "bar-chart-3": BarChart3,
  package: Package,
  star: Star,
  brain: Brain,
  "file-text": FileText
};
